spring:
  security:
    oauth2:
      client:
        registration:
          google:
            provided: google
            client-id: 484223535404-rrg6n6a89t5rk1nsvnaapej68pm6qlj8.apps.googleusercontent.com
            client-secret: VB0obg6NFn9KQ4otyzMUiLoE
            scope: profile email
          facebook:
            client-id: 267400487295308
            client-secret: ae9546faf611bb40df044c915874f23f
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/db_springboot?useSSL=false
  #    username: root
  #    password: mi-contraseña
  #    driver-class-name: com.mysql.jdbc.Driver
  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    database: mysql
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: debug

jwt:
  key: 841D8A6C80CBA4FCAD32D5367C18C53B

